{{- if index .Values "x-docker-project" }}
{{- $project := index .Values "x-docker-project" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $project }}
  labels:
    com.docker.compose.project: {{ $project }}
    com.docker.compose.manual: "true"
---
{{- end }}
