{{- range $name, $service := $.Values.services }}
{{- range $port := .ports }}
{{- if kindIs "map" . }}
{{- if index . "x-ingress" }}
{{- $ingress := index . "x-ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "common_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
spec:
  {{- if and $ingress.hosts $ingress.cert_issuer }}
  tls:
    {{- range $ingress.hosts }}
    - hosts:
        - {{ . | quote }}
      secretName: {{ include "certificate_secret_name" $name }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- $paths := default (list "/") $ingress.paths }}
          {{- range $paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $port.published | default $port.target }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
