{{- range $name, $service := $.Values.services }}
{{- if .ports }}
apiVersion: v1
kind: Service
metadata: 
  name: {{ $name }}
  labels:
    {{- include "common_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $port := .ports }}
    {{- $publishedPort := 0 }}
    {{- $targetPort := 0 }}
    {{- if kindIs "string" . }}
      {{- $portConfig := regexSplit ":" . -1 }}
      {{- $publishedPort = first $portConfig }}
      {{- $targetPort = last $portConfig }}
    {{- else if kindIs "float64" . }}
      {{ required "Single value ports must be wrapped in a string" $.Values.missing }}
    {{- else }}
      {{- $publishedPort = .published }}
      {{- $targetPort = .target }}
    {{- end}}
    - port: {{ $publishedPort }}
      targetPort: {{ $targetPort }}
    {{- end }}
  selector:
    {{- include "selector_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
---
{{- end }}
{{- end }}