{{- range $name, $service := $.Values.services }}
{{- if .ports }}
{{- range $port := .ports }}
{{- $publishedPort := 0 }}
{{- $targetPort := 0 }}
{{- $portMode := "internal" }}
{{- if kindIs "string" . }}
  {{- $portConfig := regexSplit ":" . -1 }}
  {{- $publishedPort = first $portConfig }}
  {{- $targetPort = last $portConfig }}
{{- else if kindIs "float64" . }}
  {{ required "Single value ports must be wrapped in a string" $.Values.missing }}
{{- else }}
  {{- $publishedPort = .published }}
  {{- $targetPort = .target }}
  {{- $portMode = default "internal" .mode }}
{{- end}}
{{- if not (eq $portMode "internal") }}
apiVersion: v1
kind: Service
metadata: 
  name: {{ $name }}-{{ $publishedPort }}
  labels:
    {{- include "common_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
spec:
  type: {{ include "service_type_mapping" $portMode }}
  ports:
    - port: {{ $publishedPort }}
      targetPort: {{ $targetPort }}
  selector:
    {{- include "selector_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}